from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import pyarrow as pa
import pyarrow.ipc as ipc
import requests


ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = ROOT / "data" / "raw" / "oedb"
COMPUTATIONAL_ARROW = RAW_DIR / "electrolytes.arrow"
EXPERIMENTAL_ARROW = RAW_DIR / "experimental.arrow"
COMPUTATIONAL_CSV = ROOT / "data" / "oedb_computational_properties.csv"
EXPERIMENTAL_CSV = ROOT / "data" / "oedb_experimental_raman_index.csv"
REPORT_PATH = ROOT / "data" / "oedb_report.json"

BASE_URL = "https://oedb.jp"
VERSION = "2026-05-11"
ARTICLE_DOI = "10.1038/s41524-026-02093-y"


def download(url: str, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    response = requests.get(
        url,
        timeout=60,
        headers={"User-Agent": "ionmix-oedb-sync/0.1 (+https://ionmix.cn)"},
    )
    response.raise_for_status()
    path.write_bytes(response.content)


def read_arrow(path: Path) -> pd.DataFrame:
    with pa.memory_map(str(path), "r") as source:
        try:
            table = ipc.open_file(source).read_all()
        except pa.ArrowInvalid:
            source.seek(0)
            table = ipc.open_stream(source).read_all()
    return table.to_pandas()


def clean_computational(df: pd.DataFrame) -> pd.DataFrame:
    property_cols = [
        "Ionic Conductivity (mS/cm)",
        "Viscosity (mPa·s)",
        "Cation's Diffusivity (m²/s)",
        "Anion's Diffusivity (m²/s)",
        "Solvent's Diffusivity (m²/s)",
        "Coordination Number (Cation ← Anion)",
        "Coordination Number (Cation ← Solvent)",
        "Density (g/cm³)",
    ]
    for col in property_cols:
        if col in df.columns:
            df.loc[df[col] < 0, col] = pd.NA
    df["source_name"] = "OEDB computational"
    df["source_type"] = "computed_md"
    df["source_url"] = BASE_URL
    df["source_doi"] = ARTICLE_DOI
    df["source_version"] = VERSION
    keep = [
        "id",
        "source_name",
        "source_type",
        "source_url",
        "source_doi",
        "source_version",
        "cation",
        "anion",
        "solvent",
        "Concentration (mol/kg)",
        *property_cols,
        "cation_name",
        "anion_name",
        "anion_smiles",
        "anion_pubchem_cid",
        "solvent_name",
        "solvent_smiles",
        "solvent_pubchem_cid",
    ]
    return df[[col for col in keep if col in df.columns]].copy()


def clean_experimental(df: pd.DataFrame) -> pd.DataFrame:
    df["source_name"] = "OEDB experimental Raman"
    df["source_type"] = "experimental_raman_index"
    df["source_url"] = BASE_URL
    df["source_doi"] = ARTICLE_DOI
    df["source_version"] = VERSION
    keep = [
        "id",
        "cmp_id",
        "source_name",
        "source_type",
        "source_url",
        "source_doi",
        "source_version",
        "cation",
        "anion",
        "solvent",
        "Concentration (mol/kg)",
    ]
    return df[[col for col in keep if col in df.columns]].copy()


def main() -> None:
    download(f"{BASE_URL}/data/electrolytes.arrow", COMPUTATIONAL_ARROW)
    download(f"{BASE_URL}/data/experimental.arrow", EXPERIMENTAL_ARROW)
    computational = clean_computational(read_arrow(COMPUTATIONAL_ARROW))
    experimental = clean_experimental(read_arrow(EXPERIMENTAL_ARROW))
    computational.to_csv(COMPUTATIONAL_CSV, index=False)
    experimental.to_csv(EXPERIMENTAL_CSV, index=False)

    report = {
        "source": "Open Electrolyte Database for Batteries",
        "version": VERSION,
        "article_doi": ARTICLE_DOI,
        "article_journal": "npj Computational Materials",
        "computational_rows": int(len(computational)),
        "experimental_raman_rows": int(len(experimental)),
        "computational_target_counts": {
            col: int(computational[col].notna().sum())
            for col in computational.columns
            if col.endswith(")") or col in {"Viscosity (mPa·s)", "Density (g/cm³)"}
        },
        "experimental_note": (
            "The OEDB experimental file is a Raman-spectrum index. It is public "
            "experimental data, but it is not a direct viscosity/solubility label."
        ),
        "computational_note": (
            "The OEDB computational file is generated by high-throughput molecular "
            "dynamics, so these rows are auxiliary computed labels rather than "
            "literature experimental measurements."
        ),
    }
    REPORT_PATH.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
